### ISSUE TITLE
MPEG dash Support 

### ISSUE THREAD

**Issue by syedbaqarrizvi** [streamroot/videojs-quality-picker#2]
Will it support MPeg Dash ? Because i am unable to find any example of it OR live example

**Comment by ruslandinov** [comment]
This plugin does not support MPEG-DASH. It's media engine agnostic, which means it's not aware(and should not be) of actual media engine you are using.

As you probably know, video.js doesn't support HLS or DASH out of the box, it requires a SourceHandler implementation for this. At Streamroot we created a simple [HLS SourceHandler](https://github.com/streamroot/videojs-hls.js) which is supported by this plugin.

We wanted to create a universal plugin, that's why it expects quality data to be formatted and passed to it in a specific way, which we described in the [README.md](https://github.com/streamroot/videojs-quality-picker#make-a-tech--source-handler-compatible). You can adapt any existing DASH SourceHandler(for example [videojs-contrib-dash](https://github.com/videojs/videojs-contrib-dash)) to this requirements and quality picker will work.

Regarding absence of live example -- that's definitely a very useful thing to have, so we are going to add it to the project soon.

**Comment by baqarrivi** [comment]
Hello ruslandinov,
you are awesome you always comes with solution actually we are also using  videojs-contrib-dash in our plugin you can see it here .
https://bestsongs.pk/videos/sarbjit-trailer-2016/
This means picker will work that will be great but if i am able to find any live example from your side it will be awesome . i mean i am unable to find  videojs-contrib-dash example here only able to find HLS Example. Thanks you reply from you precious time .hope we will work with this case. 

Regards 
Baqarrizvi

**Comment by ruslandinov** [comment]
In your case picker will work only if you modify `videojs-contrib-dash`. The modifications you have to do are listed here  https://github.com/streamroot/videojs-quality-picker#make-a-tech--source-handler-compatible. I'll try to make a live example with soon.
